### ISSUE TITLE
Error setting up peer node configuration

### ISSUE THREAD

**Issue by clusterfari** [nemtech/symbol-docs#618]
During the bootstrap installation, on a LInux 18.04 operating system,
I run the command 

 symbol-bootstrap start -p mainnet -a peer

and receive the following error output after entering the password:

2021-03-19T22:54:23.445Z info     Password has been provided
2021-03-19T22:54:23.498Z info     Generating config from preset mainnet
2021-03-19T22:54:23.498Z info     Assembly preset peer
2021-03-19T22:54:23.576Z info     Generating Main account...
2021-03-19T22:54:23.615Z info     Generating Transport account...
2021-03-19T22:54:23.644Z info     Generating Remote account...
2021-03-19T22:54:23.654Z info     Generating VRF account...
2021-03-19T22:54:23.659Z error    Unknown error generating the configuration. Cannot read property 'mkdir' of undefined
2021-03-19T22:54:23.660Z error    The target folder 'target' should be deleted!!!
TypeError: Cannot read property 'mkdir' of undefined
    at Function.mkdir (/usr/local/lib/node_modules/symbol-bootstrap/lib/service/BootstrapUtils.js:300:29)
    at ConfigService.run (/usr/local/lib/node_modules/symbol-bootstrap/lib/service/ConfigService.js:97:51)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    TypeError: Cannot read property 'mkdir' of undefined

Do you have an idea what could cause this problem?

**Comment by segfaultxavi** [comment]
Please open this issue in the Symbol Bootstrap repository:
https://github.com/nemtech/symbol-bootstrap/issues
