### ISSUE TITLE
Invalid ca private key while setting up the Bootstrap — Docker container inside the Docker container

### ISSUE THREAD

**Issue by alex-core-0x** [nemtech/symbol-docs#626]
Log:

```
                         _             _         _                    _         _
  ___  _   _  _ __ ___  | |__    ___  | |       | |__    ___    ___  | |_  ___ | |_  _ __  __ _  _ __
 / __|| | | || '_ ` _ \ | '_ \  / _ \ | | _____ | '_ \  / _ \  / _ \ | __|/ __|| __|| '__|/ _` || '_ \
 \__ \| |_| || | | | | || |_) || (_) || ||_____|| |_) || (_) || (_) || |_ \__ \| |_ | |  | (_| || |_) |
 |___/ \__, ||_| |_| |_||_.__/  \___/ |_|       |_.__/  \___/  \___/  \__||___/ \__||_|   \__,_|| .__/
       |___/                                                                                    |_|
2021-03-15T14:26:39.709Z info     Password has been provided
2021-03-15T14:26:39.735Z info     Generating config from preset testnet
2021-03-15T14:26:39.736Z info     Assembly preset dual
2021-03-15T14:26:39.736Z info     Custom preset file supernode.yml
2021-03-15T14:26:39.756Z info     Main Account TBCGM5M5BFP3MUOIK3L6IDICL26H6TGNT5ASEJA has been provided
2021-03-15T14:26:39.757Z info     Generating Transport account...
2021-03-15T14:26:39.804Z info     Remote Account TA7PX6PUKRCRGMTNZSJJ5YUQJQBX3KHFQGLUBSI has been provided
2021-03-15T14:26:39.809Z info     VRF Account TBSSZOC4JL6NZKDXDTA3CXQRCPMGUKK4SIWLDEI has been provided
? Enter the 64 HEX private key of the Node's 'api-node' Main account with Addres
s: TBCGM5M5BFP3MUOIK3L6IDICL26H6TGNT5ASEJA and Public Key: 776c6987cdbe53e93a5db
93a9be28f4f9060bc48be73515d1fee6391eae4440b: ***********************************
2021-03-15T14:26:39.887Z info     User for docker resolved: 0:0
2021-03-15T14:26:39.887Z error    YOU ARE RUNNING BOOTSTRAP AS ROOT!!!! THIS IS NOT RECOMMENDED!!!
2021-03-15T14:26:39.888Z info     Running image using Exec: symbolplatform/symbol-server:tools-gcc-0.10.1.8 bash createNodeCertificates.sh
time="2021-03-15T14:26:49.587726002Z" level=info msg="shim containerd-shim started" address="unix:///run/containerd/s/6d8efd157557ab7f9cfa2f2525d2edd8358aaa7ea6d8fe8327a60772c62c8212" debug=false pid=223
time="2021-03-15T14:26:50.116436919Z" level=info msg="shim reaped" id=1b319ba20784f68567b0c1507fbf5f0a0f538df7c806613db6eb4ca0ba78b193
time="2021-03-15T14:26:50.127045209Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
2021-03-15T14:26:50.973Z info     Certificate for node api-node created
2021-03-15T14:26:50.974Z error    Unknown error generating the configuration. Invalid ca private key
2021-03-15T14:26:50.974Z error    The target folder 'target' should be deleted!!!
Error: Invalid ca private key
    at Function.validateIsTrue (/usr/lib/node_modules/symbol-bootstrap/lib/service/BootstrapUtils.js:180:19)
    at CertificateService.run (/usr/lib/node_modules/symbol-bootstrap/lib/service/CertificateService.js:103:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    Error: Invalid ca private key
```

```
echo "$KEY" | symbol-bootstrap config -r -p $PRESET -a dual --password=$PASSWORD -c $PRESET_FILE
```

Specs:<br/>
Ubuntu 20.04<br/>
Docker version 19.03.8, build afacb8b7f0

See the discussion here: https://nem2.slack.com/archives/C9YKR0EUX/p1615819403229000

**Comment by segfaultxavi** [comment]
Can you please create this issue in the [Symbol Bootstrap](https://github.com/nemtech/symbol-bootstrap/issues) repository? I cannot move it there automatically.

**Comment by alex-core-0x** [comment]
> 
> 
> Can you please create this issue in the [Symbol Bootstrap](https://github.com/nemtech/symbol-bootstrap/issues) repository? I cannot move it there automatically.

Ok, created - https://github.com/nemtech/symbol-bootstrap/issues/219

You can close this one.

**Comment by segfaultxavi** [comment]
Thanks!
