### ISSUE TITLE
[symbol-bootstrap start -p bootstrap] Error

### ISSUE THREAD

**Issue by juggernoat** [nemtech/symbol-docs#669]
[reference URL]
https://docs.symbolplatform.com/ja/guides/network/creating-a-private-test-net.html

[command]
`symbol-bootstrap start -p bootstrap`

[error log]
```
2021-06-12T16:02:50.109Z info     Running image using Exec: symbolplatform/symbol-server:tools-gcc-1.0.0.0 /usr/catapult/bin/catapult.tools.votingkey --secret=HIDDEN_KEY --startEpoch=1 --endEpoch=360 --output=/votingKeys/private_key_tree1.dat
2021-06-12T16:02:50.113Z info     Running image using Exec: symbolplatform/symbol-server:tools-gcc-1.0.0.0 /usr/catapult/bin/catapult.tools.votingkey --secret=HIDDEN_KEY --startEpoch=1 --endEpoch=360 --output=/votingKeys/private_key_tree1.dat
2021-06-12T16:02:50.170Z info     Non-voting node api-node-0.
2021-06-12T16:02:51.106Z error    Unknown error generating the configuration. Command failed: docker run --rm   --env LD_LIBRARY_PATH=/usr/catapult/lib:/usr/catapult/deps -v C:\Users\debuguser\Desktop\SymbolPrivateNetwork\target\nodes\peer-node-1\votingkeys:/votingKeys:rw symbolplatform/symbol-server:tools-gcc-1.0.0.0 "/usr/catapult/bin/catapult.tools.votingkey" "--secret=4029DAA065B6D5D68E5682C52978DE3D27E957444BA5587CDF924BC2A7580261" "--startEpoch=1" "--endEpoch=360" "--output=/votingKeys/private_key_tree1.dat"
2021-06-12T16:02:51.107Z error    The target folder 'target' should be deleted!!!
Error: Command failed: docker run --rm   --env LD_LIBRARY_PATH=/usr/catapult/lib:/usr/catapult/deps -v C:\Users\debuguser\Desktop\SymbolPrivateNetwork\target\nodes\peer-node-1\votingkeys:/votingKeys:rw symbolplatform/symbol-server:tools-gcc-1.0.0.0 "/usr/catapult/bin/catapult.tools.votingkey" "--secret=4029DAA065B6D5D68E5682C52978DE3D27E957444BA5587CDF924BC2A7580261" "--startEpoch=1" "--endEpoch=360" "--output=/votingKeys/private_key_tree1.dat"
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 132,
  signal: null,
  cmd: 'docker run --rm   --env LD_LIBRARY_PATH=/usr/catapult/lib:/usr/catapult/deps -v C:\\Users\\debuguser\\Desktop\\SymbolPrivateNetwork\\target\\nodes\\peer-node-1\\votingkeys:/votingKeys:rw symbolplatform/symbol-server:tools-gcc-1.0.0.0 "/usr/catapult/bin/catapult.tools.votingkey" "--secret=4029DAA065B6D5D68E5682C52978DE3D27E957444BA5587CDF924BC2A7580261" "--startEpoch=1" "--endEpoch=360" "--output=/votingKeys/private_key_tree1.dat"',
  stdout: '',
  stderr: ''
}
    Error: Command failed: docker run --rm   --env LD_LIBRARY_PATH=/usr/catapult/lib:/usr/catapult/deps -v
    C:\Users\debuguser\Desktop\SymbolPrivateNetwork\target\nodes\peer-node-1\votingkeys:/votingKeys:rw
    symbolplatform/symbol-server:tools-gcc-1.0.0.0 "/usr/catapult/bin/catapult.tools.votingkey"
    "--secret=4029DAA065B6D5D68E5682C52978DE3D27E957444BA5587CDF924BC2A7580261" "--startEpoch=1" "--endEpoch=360"
    "--output=/votingKeys/private_key_tree1.dat"
    Code: 132
```

[environment]
```
Windows 10 Pro
>docker --version
    Docker version 19.03.12, build 48a66213fe
>node --version
    v14.16.0

```
[Supplement]
Can be executed independently
`C:\Users\debuguser\Desktop\SymbolPrivateNetwork>docker run --rm   --env LD_LIBRARY_PATH=/usr/catapult/lib:/usr/catapult/deps -v C:\\Users\\debuguser\\Desktop\\SymbolPrivateNetwork\\target\\nodes\\peer-node-1\\votingkeys:/votingKeys:rw symbolplatform/symbol-server:tools-gcc-1.0.0.0 "/usr/catapult/bin/catapult.tools.votingkey" "--secret=4029DAA065B6D5D68E5682C52978DE3D27E957444BA5587CDF924BC2A7580261" "--startEpoch=1" "--endEpoch=360" "--output=/votingKeys/private_key_tree1.dat"`

**Comment by juggernoat** [comment]
It worked on another Windows computer.
It may have been due to system settings.

Thank you very much.
